### ISSUE TITLE
Rename package to `epidatpy`

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epidatpy#13]
See https://github.com/cmu-delphi/delphi-epidata-r/issues/31.  The R package rename is currently in progress.  The Python package is currently not being worked on.

Following [the renaming process in Logan's comment](https://github.com/cmu-delphi/epidatr/issues/31#issuecomment-1195732206)

- [x] #16 
- [x] Ping relevant channels with a notice.
- [x] Create branch holding the old name package: [`delphi_epidata-before-rename`](https://github.com/cmu-delphi/delphi-epidata-py/tree/delphi_epidata-before-rename).
- [ ] Pre-switch anything in production using delphi.epidata to this branch. [removed irrelevant epidatr stuff] Schedule transition back to the main branch + renaming [delphi_epidata -> epidatpy] for these things.
- [x] #17 
- [ ] #15
- [ ] Downstream, perform the scheduled switches to rely on main branch & epidatpy package name.

**Comment by brookslogan** [comment]
You may also need to look for references to the R package name in the Python package repo and rename those as well.  Just noticed [this](https://github.com/cmu-delphi/epidatr/blob/dev/_pkgdown.yml) in the R pkg repo.

**Comment by dshemetov** [comment]
Didn't find anything searching for "R package" and `cmu-delphi` and `delphi-epidata-r`.
