### ISSUE TITLE
Rename repo to `epidatpy`

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/epidatpy#17]
Partially addresses #13.

**Comment by dshemetov** [comment]
Need someone with admin access to this repo (@krivard I'm willing to push this along, if you pass me privs).

**Comment by brookslogan** [comment]
Please ping me when this is completed, so I can update the R pkg repo's pointer to this repo.  (I'm waiting for this to actually occur because apparently pkgdown deployment can break without CI checks failing, and I don't know if broken hyperlinks are one of the things that will break pkgdown.)

**Comment by krivard** [comment]
Done!
